### ISSUE TITLE
Error on "options" on logConfiguration declaration Datadog documentation

### ISSUE THREAD

**Issue by kiros-sc** [aws-samples/amazon-ecs-firelens-examples#12]
I found the following error on your "amazon-ecs-firelens-examples/examples/fluent-bit/datadog/" README.md. If you check the declaration of options inside "logConfiguration" the key "name" is written on lowercase,
```
"logConfiguration": {
	"logDriver":"awsfirelens",
	"options": {
	   "name": "datadog",
	   "apiKey": "<DATADOG_API_KEY>",
	   "dd_service": "my-httpd-service",
	   "dd_source": "httpd",
	   "dd_tags": "project:example",
	   "provider": "ecs"
   }
},
```

 and when I tried to execute my task definition I keep getting the following error: 

```
Error
unable to generate firelens config: unable to apply log options of container app to firelens config: missing output key Name which is required for firelens configuration of type fluentbit
```

I finally found another doc from a random user, and on his example he was using this declaration: 

```"logConfiguration": {
	"logDriver":"awsfirelens",
	"options": {
	   "Name": "datadog",
	   "apiKey": "<DATADOG_API_KEY>",
	   "dd_service": "my-httpd-service",
	   "dd_source": "httpd",
	   "dd_tags": "project:example",
	   "provider": "ecs"
   }
},
```

When I changed my own "taskdefinition", changing the **"name"** option to **"Name"**, the issue was gone.
It's just a small error on the documentation but I believe it will help others if fixed.

**Comment by PettitWesley** [comment]
@kiros-sc Thanks for alerting us to this, it indeed should be `Name` not `name.
