### ISSUE TITLE
Encountered unsupported property containerDefinitions

### ISSUE THREAD

**Issue by agentmilindu** [aws-samples/amazon-ecs-firelens-examples#23]
https://github.com/aws-samples/amazon-ecs-firelens-examples/blob/b52b737b6490903ae5769dae5390b73e0084dd36/examples/fluent-bit/kinesis-firehose/task-definition.json#L5

This should be changed from `containerDefinitions` to  `ContainerDefinitions`, unless the following error occurs. 

![Screenshot from 2020-02-17 19-37-29](https://user-images.githubusercontent.com/1391468/74660959-18810980-51bd-11ea-8ab1-f71716c68126.png)

**Comment by allisaurus** [comment]
Closing per [this comment](https://github.com/aws-samples/amazon-ecs-firelens-examples/pull/24#issuecomment-587168474) - lower case is intentional as it matches the input for the ECS RunTask API
