### ISSUE TITLE
docker pull fails

### ISSUE THREAD

**Issue by yenkaykiran** [aws-samples/amazon-ecs-firelens-examples#28]
We need to use the docker image through our internal artifactory docker repository. When I try to pull this image, I get below error;

```
docker pull 533243300146.dkr.ecr.us-east-1.amazonaws.com/newrelic/logging-firelens-fluentbit

Using default tag: latest
Error response from daemon: Get https://533243300146.dkr.ecr.us-east-1.amazonaws.com/v2/newrelic/logging-firelens-fluentbit/manifests/latest: no basic auth credentials
```

Is there a way to be able to pull this image so that we can push to our internal artifactory after that.

**Comment by CarmenAPuccio** [comment]
Take a look at this documentation which should help you.

- [Troubleshooting Errors with Docker Commands When Using Amazon ECR](https://docs.aws.amazon.com/AmazonECR/latest/userguide/common-errors-docker.html#error-403)
- [Pulling an Image](https://docs.aws.amazon.com/AmazonECR/latest/userguide/docker-pull-ecr-image.html)

Be sure to read the registry authentication piece.
