### ISSUE TITLE
Multiline logs configuration not working

### ISSUE THREAD

**Issue by arunpatyal** [aws-samples/amazon-ecs-firelens-examples#30]
Referring to the details in https://github.com/aws-samples/amazon-ecs-firelens-examples/tree/master/examples/fluentd/multiline-logs, I have created a service but the multi-line logs are not being combined. I am trying to send logs to Sumo Logic.

Here is the **docker** file:

>FROM fluent/fluentd:v1.11.0-debian-1.0
ADD extra.conf /extra.conf
USER root
RUN buildDeps="sudo make gcc g++ libc-dev" \
 && apt-get update \
 && apt-get install -y --no-install-recommends $buildDeps \
 && gem install fluent-plugin-concat \
 && gem install fluent-plugin-cloudwatch-logs \
 && gem install fluent-plugin-sumologic_output \
 && gem install fluent-plugin-out-http \
 && gem sources --clear-all \
 && rm -rf /tmp/* /var/tmp/* /usr/lib/ruby/gems/*/cache/*.gem
USER fluent

**extra.conf**

```
 <filter app-firelens**>
   @type concat
   key log
   stream_identity_key container_id
   multiline_start_regexp /^/[DockerLogGenerator/]/
 </filter>
 #<match app-firelens**>
 #@type sumologic
 #endpoint https://collectors.sumologic.com/receiver/v1/http/XXXXXX
 #source_category ECS/FireLens/Custom/Fargatewoz
 #source_name FireLensCustom
 #</match>

```

Note the sumologic plugin above, I have tried with sumologic plugin, fluentd http out plugin and cloudwatch plugin, same result each time.

Task definition:

```
{
    "requiresCompatibilities": [
        "FARGATE"
    ],
    "containerDefinitions": [
        {
            "image": "arunpatyal/firelens-sumo-logger:11",
            "name": "log_router_sumo_file_config",
            "memory": 100,
            "essential": true,
            "firelensConfiguration": {
                "type": "fluentd",
                "options": {
                    "enable-ecs-log-metadata": "true",
                    "config-file-type": "file",
                    "config-file-value": "/extra.conf"
                }
            },
            "logConfiguration": {
                "logDriver": "awslogs",
                "options": {
                    "awslogs-group": "awslogs-ecs-fargate-sumo",
                    "awslogs-region": "us-west-1",
                    "awslogs-stream-prefix": "awslogs-ecs-fargate-sumo"
            }
          }
        },
  		 {
  			 "essential": true,
  			 "image": "arunpatyal/firelens-log-generator:1",
  			 "name": "app",
  			 "logConfiguration": {
                   "logDriver":"awsfirelens",
                   "options": {
                    "log_group_name": "firelens-log-group",
                    "log_stream_name": "firelens-log-stream",
                    "@type": "cloudwatch_logs",
                    "region": "us-west-1"
                   }

  			},
  			"memory": 100
  		}
    ],
    "family": "firelens-service",
    "executionRoleArn": "arn:aws:iam::xxxxxxxxxx:role/ecsTaskExecutionRole",
    "cpu": "256",
    "memory": "512",
    "volumes": [],
    "placementConstraints": [],
    "taskRoleArn": "arn:aws:iam::xxxxxxxxxx:role/ecs_task_iam_role",
    "networkMode": "awsvpc"
}
```

The firelens-log-generator:1 is based on https://github.com/DenisBiondic/DockerLogGenerator with slight modifications, it generates logs in the below format:

> [DockerLogGenerator] Current Time: 2020-07-09 05:04:40.092007251 +0000 UTC m=+35.001891793
> [DockerLogGenerator] Multiline: 2020-07-09 05:04:40.092052436 +0000 UTC m=+35.001936973
>  This is the second line
> This is the third line
> [DockerLogGenerator] Current Time: 2020-07-09 05:04:45.09222899 +0000 UTC m=+40.002113544

Here is the output from cloudwatch:

```
{
    "container_id": "d0c83eb7e9d94aff0ca7e25f54048031740712c5f52e9e4e3b6b73988bf57afa",
    "container_name": "/ecs-firelens-service-11-app-90d782cd98eb808d1700",
    "source": "stdout",
    "log": "[DockerLogGenerator] Current Time: 2020-07-09 05:04:40.092007251 +0000 UTC m=+35.001891793",
    "ecs_cluster": "arn:aws:ecs:us-west-1:XXXXXXXX:cluster/fargate-cluster",
    "ecs_task_arn": "arn:aws:ecs:us-west-1:XXXXXXXXX:task/38e847e2-2d9f-4e58-88e0-cd875d6f40d6",
    "ecs_task_definition": "firelens-service:11"
}
{
    "log": "[DockerLogGenerator] Multiline: 2020-07-09 05:04:40.092052436 +0000 UTC m=+35.001936973",
    "container_id": "d0c83eb7e9d94aff0ca7e25f54048031740712c5f52e9e4e3b6b73988bf57afa",
    "container_name": "/ecs-firelens-service-11-app-90d782cd98eb808d1700",
    "source": "stdout",
    "ecs_cluster": "arn:aws:ecs:us-west-1:XXXXXXX:cluster/fargate-cluster",
    "ecs_task_arn": "arn:aws:ecs:us-west-1:XXXXXXXXX:task/38e847e2-2d9f-4e58-88e0-cd875d6f40d6",
    "ecs_task_definition": "firelens-service:11"
}
{
    "container_id": "d0c83eb7e9d94aff0ca7e25f54048031740712c5f52e9e4e3b6b73988bf57afa",
    "container_name": "/ecs-firelens-service-11-app-90d782cd98eb808d1700",
    "source": "stdout",
    "log": " This is the second line",
    "ecs_cluster": "arn:aws:ecs:us-west-1:XXXXXXXXX:cluster/fargate-cluster",
    "ecs_task_arn": "arn:aws:ecs:us-west-1:XXXXXXXXX:task/38e847e2-2d9f-4e58-88e0-cd875d6f40d6",
    "ecs_task_definition": "firelens-service:11"
}
{
    "container_id": "d0c83eb7e9d94aff0ca7e25f54048031740712c5f52e9e4e3b6b73988bf57afa",
    "container_name": "/ecs-firelens-service-11-app-90d782cd98eb808d1700",
    "source": "stdout",
    "log": "This is the third line",
    "ecs_cluster": "arn:aws:ecs:us-west-1:XXXXXXXXXX:cluster/fargate-cluster",
    "ecs_task_arn": "arn:aws:ecs:us-west-1:XXXXXXXXX:task/38e847e2-2d9f-4e58-88e0-cd875d6f40d6",
    "ecs_task_definition": "firelens-service:11"
}
{
    "container_name": "/ecs-firelens-service-11-app-90d782cd98eb808d1700",
    "source": "stdout",
    "log": "[DockerLogGenerator] Current Time: 2020-07-09 05:04:45.09222899 +0000 UTC m=+40.002113544",
    "container_id": "d0c83eb7e9d94aff0ca7e25f54048031740712c5f52e9e4e3b6b73988bf57afa",
    "ecs_cluster": "arn:aws:ecs:us-west-1:XXXXXXXX:cluster/fargate-cluster",
    "ecs_task_arn": "arn:aws:ecs:us-west-1:XXXXXXXXX:task/38e847e2-2d9f-4e58-88e0-cd875d6f40d6",
    "ecs_task_definition": "firelens-service:11"
}
```

I have also tried with http out as below:

```
"logConfiguration": {"logDriver":"awsfirelens","options": 
{
"endpoint" :"https://collectors.sumologic.com/receiver/v1/http/XXXXXXX",
"endpoint_url" : "https://collectors.sumologic.com/receiver/v1/http/XXXXXX",
"@type" : "http"
}
```

Please let me know if I am missing anything.

**Comment by PettitWesley** [comment]
@arunpatyal I am pretty sure the regex is the problem. Always use Rubular to test regular expressions with Fluent: https://rubular.com/

The expression should be:

```
/^\[DockerLogGenerator\]/
```

The `[` and `]` need to be escaped to be literal characters, otherwise they are interpreted as a character set.

**Comment by arunpatyal** [comment]
@PettitWesley AFAIR, I fixed the regex but it still was missed. After fixing it, it seems to work. I am working to get Java logs as well, as defined in the example, but facing some issues, will double check the regex again.

Thanks.

**Comment by arunpatyal** [comment]
Well, it worked for cloudwatch and http out but in http out plugin if I try to set format as JSON in http out plugin it gives following error in fluentd logs:

> 2020-07-10 03:09:55 +0000 [error]: #0 unexpected error in msgpack payload error="undefined method `map' for #<String:0x00007f61a50c7868>\nDid you mean?  tap"

> 2020-07-10 03:09:10 +0000 [warn]: #0 emit transaction failed: error_class=NoMethodError error="undefined method `map' for #<String:0x00007f61a54d9870>\nDid you mean?  tap" location="/usr/local/lib/ruby/2.6.0/uri/common.rb:419:in `encode_www_form'" tag="app-firelens-9ad25fd2-e9b2-489c-80c1-1a8b636517d2"

I am trying like this, is this correct?
```
    "logConfiguration": {
    "logDriver":"awsfirelens",
    "options": {
    "endpoint" :"https://collectors.sumologic.com/receiver/v1/http/xxxxxx",
    "endpoint_url" : "https://collectors.sumologic.com/receiver/v1/http/xxxx",
    "@type" : "http",
    "format": "json"
     }
```

**Comment by PettitWesley** [comment]
@arunpatyal It looks ok to me, I am not sure about that error.

Format is usually specified in a separate XML block: https://docs.fluentd.org/formatter

It might be better to specify the output in your extra config file instead of the logConfiguration options:

```
<match app-firelens**>
    @type http
    delivery_stream_name demo-stream
    endpoint_url https://collectors.sumologic.com/receiver/v1/http/xxxx
    endpoint  https://collectors.sumologic.com/receiver/v1/http/xxxxxx
    <format>
        @type json
    </format>
</match>
```

**Comment by arunpatyal** [comment]
Yes, that works. But I wanted http out plugin with JSON output to work from task definition itself in a scenario where I do not need to create a custom fluentd image.

**Comment by arunpatyal** [comment]
Closing, as the original issue is resolved by using sumologic output plugin.
