### ISSUE TITLE
Different behaviour for Customized FluentBit image for Fargate 1.4.0 and 1.3.0.

### ISSUE THREAD

**Issue by arunpatyal** [aws-samples/amazon-ecs-firelens-examples#35]
As Fargate doesn't support S3 custom config, I am creating a custom image for FluentBit as described here: https://help.sumologic.com/03Send-Data/Collect-from-Other-Data-Sources/AWS_Fargate_log_collection#optional-support-for-multiple-http-headers This results in Sumo Logic logger as a sidecar container and the main application container to use awsfirelens without any further options. With Fargate 1.3.0 everything works.

However, upgrading to Fargate 1.4.0 the main application container fails with error:

`CannotStartContainerError: ResourceInitializationError: failed to initialize logging driver: failed to get fluentd logdriver arguments: logging driver specified of container vernemq`

When specifying "Name" attribute to the main containers log configuration options: 

- Name: forward Sidecar starts and logs are transported to sumo logic, but the logs seem to loop and the sidecar container goes out of memory after half a minute.
- Name: http The logs go to sumologic. But it seems that there are 2 output configuration now. One working to sumo. And one other with no valid configuration: 

```
[2020/08/10 15:15:34] [error] [io] TCP connection failed: 127.0.0.1:80 (Connection refused) 
[2020/08/10 15:15:33] [ info] [output:http:http.0] endpoint1.collection.eu.sumologic.com:443, HTTP status=200
```

What is the correct option configuration with Fargate 1.4.0 and why is the empty option not working like with Fargate 1.3.0?

**Comment by PettitWesley** [comment]
@arunpatyal Can you share your task definitions? Nothing should have changed in Fargate 1.4.0

**Comment by arunpatyal** [comment]
```
{
    "requiresCompatibilities": [
        "FARGATE"
    ],
    "containerDefinitions": [
        {
            "image": "arunpatyal/aws-fluent-bit:latest",
            "name": "log_router_sumo",
            "memory": 100,
            "essential": true,
            "firelensConfiguration": {
                "type": "fluentbit",
                "options": {
                    "enable-ecs-log-metadata": "true",
                    "config-file-type": "file",
                    "config-file-value": "/fluent-bit/etc/custom/fluent-bit-custom.conf"
                }
            },
            "logConfiguration": {
                "logDriver": "awslogs",
                "options": {
                    "awslogs-group": "awslogs-ecs-fargate-sumo",
                    "awslogs-region": "us-west-1",
                    "awslogs-stream-prefix": "awslogs-ecs-fargate-sumo"
            }
          }
        },
  		 {
  			 "essential": true,
  			 "image": "httpd",
  			 "name": "app",
         "portMappings": [
                {
                    "containerPort": 80,
                    "hostPort": 80,
                    "protocol": "tcp"
                }
            ],
         "entryPoint": [
                "sh",
		              "-c"
            ],
         "command": [
                "/bin/sh -c \"echo '<html> <head> <title>Amazon ECS Sample App</title> <style>body {margin-top: 40px; background-color: #333;} </style> </head><body> <div style=color:white;text-align:center> <h1>Amazon ECS Sample App</h1> <h2>Congratulations!</h2> <p>Your application is now running on a container in Amazon ECS.</p> </div></body></html>' >  /usr/local/apache2/htdocs/index.html && httpd-foreground\""
            ],
  			 "logConfiguration": {
                            "logDriver":"awsfirelens"
  			},
  			"memory": 100
  		}
    ],
    "family": "firelens-sumo-fargate-new-version",
    "executionRoleArn": "arn:aws:iam::XXXXXXXX:role/ecsTaskExecutionRole",
    "cpu": "256",
    "memory": "512",
    "volumes": [],
    "placementConstraints": [],
    "taskRoleArn": "arn:aws:iam::XXXXXXX:role/ecs_task_iam_role",
    "networkMode": "awsvpc"
}
```
The custom image has the custom config file:
`COPY fluent-bit-custom.conf /fluent-bit/etc/custom`

The custom config file:
```
[OUTPUT]
    Name       http
    Match      *
    Host       <HOST>
    URI        <URI>
    Port       443
    Header     X-Sumo-Category ECS/FireLens/Custom/Fargate
    Header     X-Sumo-Name ECSFireLensCustom
    tls        on
    tls.verify off
    Format     json_lines
```

**Comment by arunpatyal** [comment]
@PettitWesley Were you able to take a look at this?

**Comment by PettitWesley** [comment]
> When specifying "Name" attribute to the main containers log configuration options:

If you specify LogConfiguration options, it will get converted into an output. This will be appended to your extra config file- which means you'll have two outputs, as you saw. If you don't specify anything but `name`, then you'll get an empty output.

Basically, there's no reason to believe that adding anything in the LogConfiguration will help..

> CannotStartContainerError: ResourceInitializationError: failed to initialize logging driver: failed to get fluentd logdriver arguments: logging driver specified of container vernemq

Your Task Def and config looks fine...


 I will try to see if I can repro this...

**Comment by PettitWesley** [comment]
@arunpatyal I think I just realized what it is... its the config file path:

```
/fluent-bit/etc/custom/fluent-bit-custom.conf
```

The entire `/fluent-bit/etc/` folder is reserved for use by FireLens; you have to put the config in a different directory. I think our docs are not very clear on this, if changing the path fixes the problem, I will make sure the docs are updated.

**Comment by PettitWesley** [comment]
Never mind, its the Dockerfile copy line:

```
COPY fluent-bit-custom.conf /fluent-bit/etc/custom
```

This creates a file at `/fluent-bit/etc/custom` in your dockerfile. You want:

```
COPY fluent-bit-custom.conf /fluent-bit/etc/custom/fluent-bit-custom.conf
```

**Comment by arunpatyal** [comment]
Thanks @PettitWesley. I am testing the suggested changes.
