### ISSUE TITLE
The value of total_file_size in task-definition.json for S3 output plugin is invalid.

### ISSUE THREAD

**Issue by tam0ri** [aws-samples/amazon-ecs-firelens-examples#39]
https://github.com/aws-samples/amazon-ecs-firelens-examples/blob/edc932f7fb619664ee79d1ae92f860164de5272e/examples/fluent-bit/s3/task-definition.json#L34

In this task-definition.json, `total_file_size` is specified as 1M. However, default value of `upload_chunk_size` is 5,242,880 bytes and `upload_chunk_size` can not be larger than `total_file_size`. Also, `upload_chunk_size` must be at least 5,242,880 bytes. I guess that this is caused by following example in Fluent Bit's document.
https://docs.fluentbit.io/manual/pipeline/outputs/s3#using-s3-without-persisted-disk
```
[OUTPUT]
     Name s3
     Match *
     bucket your-bucket
     region us-east-1
     total_file_size 1M
     upload_timeout 1m
```

So I just created the issue on fluent-bit-docs repository side.
https://github.com/fluent/fluent-bit-docs/issues/411

**Comment by PettitWesley** [comment]
Thank you for noticing this... as I explained in a comment on your PR, use_put_object is supposed to be enabled in the config: https://github.com/aws-samples/amazon-ecs-firelens-examples/pull/40

I will go and update the docs repo as well
