### ISSUE TITLE
send to AWS Elasticsearch multiline

### ISSUE THREAD

**Issue by xuxu-ning** [aws-samples/amazon-ecs-firelens-examples#43]
when the log destination is AWS Elasticsearch service, using fluent bit
the log can not combine multiline message

**Comment by PettitWesley** [comment]
@June3Ningxu I need more details....

Fluent Bit only supports multiline in the tail input: https://docs.fluentbit.io/manual/pipeline/inputs/tail

Plugins are independent in Fluent Bit's architecture- so the tail input works independently of the elasticsearch output. Thus, multiline log parsing in the tail input will work with the elasticsearch output.

Please make sure you are using the latest version, there were some bugs in the first release that contained multiline support.

**Comment by zhonghui12** [comment]
The issue will be closed. If you have more questions, you can re-open it.

Thanks.
