### ISSUE TITLE
Feature Request: add Kinesis Data Streams Example

### ISSUE THREAD

**Issue by ravinaik1312** [aws-samples/amazon-ecs-firelens-examples#53]
I'm not sure if Kinesis Data streams is directly supported with firelens, but looking at the documentation it could be done if it reads the fluentbit config file that has the output as kinesis data stream. It would be great to verify this by adding an example for sending logs to Kinesis data stream.

**Comment by PettitWesley** [comment]
Sorry about this.. we meant to add one a long time ago. We will get to it. In the meantime, you can literally just use the firehose example and replace the plugin name: https://github.com/aws-samples/amazon-ecs-firelens-examples/tree/mainline/examples/fluent-bit/kinesis-firehose

Please note that there are 2 kinesis plugins in AWS for Fluent Bit:
- https://github.com/aws/amazon-kinesis-firehose-for-fluent-bit
- https://docs.fluentbit.io/manual/pipeline/outputs/firehose

**Comment by ravinaik1312** [comment]
Thanks for the response. I was able to take it for a spin after I understood that firelens is essentially just syntactic sugar on top of fargate, so whatever fluentbit supports, we should be able to incorporate it with firelens. I will drop in a PR soon so that others can refer to it. We can close this issue when I submit a PR and it gets merged.

**Comment by PettitWesley** [comment]
@ravinaik1312 Thanks!

**Comment by hossain-rayhan** [comment]
Closed by #54
