### ISSUE TITLE
space after - in health check script fails the health check

### ISSUE THREAD

**Issue by r0b0ji** [aws-samples/amazon-ecs-firelens-examples#76]
The space between `-` and `f` in curl command is incorrect and fails, causing health check to fail. In the command it should be `-f` together.

https://github.com/aws-samples/amazon-ecs-firelens-examples/blob/7b663ea48b978d3298f6da878396f091569aa4f7/examples/fluent-bit/health-check/task-definition-output-metrics-healthcheck.json#L21

**Comment by PettitWesley** [comment]
Fixed. Thanks!
